# Generated by Django 5.0.7 on 2026-09-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(default='About MedEx', max_length=80)),
                ('title', models.CharField(default='Who We Are', max_length=150)),
                ('paragraph_1', models.TextField(help_text='Supports basic HTML for emphasis, e.g. <strong>bold text</strong>.')),
                ('paragraph_2', models.TextField(blank=True, help_text='Supports basic HTML.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('badge_icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)')], default='shield', max_length=20)),
                ('badge_title', models.CharField(blank=True, help_text="e.g. 'NABH & ISO Compliant'", max_length=100)),
                ('badge_subtitle', models.CharField(blank=True, help_text="e.g. 'Audited calibration precision'", max_length=150)),
            ],
            options={
                'verbose_name': 'About Section (Homepage)',
                'verbose_name_plural': 'About Section (Homepage)',
            },
        ),
        migrations.CreateModel(
            name='EcosystemPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)')], default='link', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('bullets', models.TextField(help_text='One bullet point per line.')),
                ('link_label', models.CharField(blank=True, help_text="e.g. 'Field Verified'", max_length=80)),
                ('link_url', models.URLField(blank=True, help_text='Leave blank to render as plain text (no link).')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ecosystem Pillar (Homepage)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OperatingPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)')], default='shield', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Operating Pillar (Homepage)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vision_text', models.TextField()),
                ('mission_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Vision & Mission',
                'verbose_name_plural': 'Vision & Mission',
            },
        ),
        migrations.AddField(
            model_name='companystat',
            name='icon',
            field=models.CharField(blank=True, choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)')], help_text="Used by the homepage 'Who We Are' stat cards. Optional elsewhere.", max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='interested_in',
            field=models.CharField(blank=True, help_text="Free-text value from the 'Select Service/Product' dropdown on the site.", max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_badge_1',
            field=models.CharField(blank=True, help_text="e.g. 'Trusted Platform'", max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_badge_2',
            field=models.CharField(blank=True, help_text="e.g. 'Patient-Centric'", max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_badge_3',
            field=models.CharField(blank=True, help_text="e.g. 'Better Health Outcomes'", max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Our Products', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optional photo shown in the hero banner instead of the default device graphic.', null=True, upload_to='products/hero/'),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text="e.g. 'Connected Care. Empowered Patients.'", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text="Short line next to the hero device graphic, e.g. 'Your Health In Your Hands Anytime Anywhere'.", max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_title',
            field=models.CharField(blank=True, help_text="e.g. 'Digital Healthcare Solutions for a Healthier Tomorrow'. Falls back to a default if blank.", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight_features',
            field=models.TextField(blank=True, help_text="Homepage-only bullet points (one per line) for this product's highlight card. Independent of the full product page content."),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight_link_label',
            field=models.CharField(blank=True, help_text="Homepage-only call-to-action text, e.g. 'Explore Remote Care Suite'.", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.TextField(blank=True, help_text='One feature per line — rendered as the two-column checklist in the Overview tab.'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='badge_text',
            field=models.CharField(blank=True, help_text="e.g. 'Verified Bio-Engineer'", max_length=80),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_leadership',
            field=models.BooleanField(default=False, help_text="Show in the homepage 'Our Leadership' section."),
        ),
        migrations.AddField(
            model_name='teammember',
            name='quote',
            field=models.CharField(blank=True, help_text='Short pull-quote shown on the homepage.', max_length=250),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, help_text="Qualification/credentials line, e.g. 'DBCE, B.E (Bio Medical)'", max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='years_text',
            field=models.CharField(blank=True, help_text="e.g. '10+ Years Biomedical Leadership'", max_length=80),
        ),
        migrations.AlterField(
            model_name='companystat',
            name='value',
            field=models.CharField(help_text="e.g. '500+', '24/7', 'Trusted'", max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Full description shown in the Overview tab on the product page.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text="One 'Label: Value' pair per line, e.g. 'Platform: iOS & Android (Mobile App)'. Rendered as the two-column table in the Specifications tab."),
        ),
    ]
