# Generated by Django 5.0.7 on 2026-09-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutsection_ecosystempillar_operatingpillar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(default='MedEx Biomed', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Upload brand logo for navbar and footer.', null=True, upload_to='settings/')),
                ('address', models.CharField(default='Chennai | Madurai | Others', max_length=250)),
                ('phone', models.CharField(default='+91 (0) 44 2345 6789', max_length=30)),
                ('email', models.EmailField(default='contact@medexbiomed.com', max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
