# Generated by Django 5.0.7 on 2026-09-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission_title', models.CharField(default='Our mission', max_length=100)),
                ('mission_text', models.TextField(blank=True)),
                ('approach_title', models.CharField(default='How we work', max_length=100)),
                ('approach_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='PageIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('about', 'About Us page'), ('services', 'Services page'), ('contact', 'Contact Us page')], max_length=20, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cta_title', models.CharField(blank=True, help_text='Optional bottom CTA banner heading.', max_length=200)),
                ('cta_text', models.TextField(blank=True, help_text='Optional bottom CTA banner body text.')),
            ],
            options={
                'verbose_name': 'Page Intro',
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.CharField(blank=True, default='Mon–Sat, 9:00am – 7:00pm', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.CharField(blank=True, default='Precision biomedical engineering. Connected healthcare. Better tomorrows.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='MedEx', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="Digits only with country code, no spaces or symbols, e.g. '910000000000'.", max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, help_text="e.g. 'Chennai | Madurai | Others'", max_length=250),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown in the navbar and footer. If left blank, the site name is shown as text instead.', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, help_text="Include country code, e.g. '+91 00000 00000'", max_length=30),
        ),
    ]
