# Generated by Django 5.0.7 on 2026-09-19 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutpagecontent_pageintro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('nav_label', models.CharField(help_text="Short label shown in the tab bar, e.g. 'AMC & Maintenance'.", max_length=100)),
                ('nav_icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='wrench', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero_eyebrow', models.CharField(blank=True, default='Our Services', max_length=60)),
                ('hero_title_main', models.CharField(help_text="e.g. 'Equipment ' (the non-highlighted part).", max_length=150)),
                ('hero_title_highlight', models.CharField(blank=True, help_text="e.g. 'Installation & Support' (shown in red).", max_length=150)),
                ('hero_subtitle', models.CharField(blank=True, max_length=250)),
                ('hero_badge_1_icon', models.CharField(blank=True, choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], max_length=20)),
                ('hero_badge_1_text', models.CharField(blank=True, max_length=60)),
                ('hero_badge_2_icon', models.CharField(blank=True, choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], max_length=20)),
                ('hero_badge_2_text', models.CharField(blank=True, max_length=60)),
                ('hero_badge_3_icon', models.CharField(blank=True, choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], max_length=20)),
                ('hero_badge_3_text', models.CharField(blank=True, max_length=60)),
                ('hero_cta_label', models.CharField(blank=True, help_text="Optional hero button, e.g. 'Request Training'.", max_length=60)),
                ('hero_tagline', models.TextField(blank=True, help_text='Short lines shown in the floating hero card, one per line.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/hero/')),
                ('overview_title', models.CharField(blank=True, default='Service Overview', max_length=150)),
                ('overview_subtitle', models.CharField(blank=True, max_length=250)),
                ('overview_description', models.TextField(blank=True)),
                ('process_title', models.CharField(blank=True, default='Our Process', max_length=150)),
                ('process_subtitle', models.CharField(blank=True, max_length=250)),
                ('equipment_title', models.CharField(blank=True, help_text='Leave blank to hide this section.', max_length=150)),
                ('equipment_subtitle', models.CharField(blank=True, max_length=250)),
                ('cta_icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='headset', max_length=20)),
                ('cta_title', models.CharField(blank=True, default='Need Support?', max_length=150)),
                ('cta_subtitle', models.CharField(blank=True, max_length=250)),
                ('form_title', models.CharField(blank=True, default='Support & Demo Request', max_length=150)),
                ('form_description', models.TextField(blank=True)),
                ('form_type', models.CharField(choices=[('support_demo', 'Support & Demo Request (equipment/product fields)'), ('training_enquiry', 'Training Enquiry (course/schedule fields)'), ('general', 'General enquiry (name, email, message only)')], default='support_demo', max_length=20)),
            ],
            options={
                'verbose_name': 'Services Page Tab',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Extra fields from richer enquiry forms (e.g. product/model/serial number, training preferences), formatted as plain text.'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='badge_icon',
            field=models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='shield', max_length=20),
        ),
        migrations.AlterField(
            model_name='companystat',
            name='icon',
            field=models.CharField(blank=True, choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], help_text="Used by the homepage 'Who We Are' stat cards. Optional elsewhere.", max_length=20),
        ),
        migrations.AlterField(
            model_name='ecosystempillar',
            name='icon',
            field=models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='link', max_length=20),
        ),
        migrations.AlterField(
            model_name='operatingpillar',
            name='icon',
            field=models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='shield', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='check', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/features/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_items', to='core.servicepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='monitor', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='core.servicepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='core.servicepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
