# Generated by Django 5.0.7 on 2026-09-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicepage_contactmessage_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='resume',
            field=models.FileField(blank=True, help_text="Uploaded from the Career tab's application form.", null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='servicefeatureitem',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Leave blank to link to the Contact page.'),
        ),
        migrations.AddField(
            model_name='servicefeatureitem',
            name='background_text',
            field=models.TextField(blank=True, help_text="'Target Background' description. Role cards only."),
        ),
        migrations.AddField(
            model_name='servicefeatureitem',
            name='focus_text',
            field=models.TextField(blank=True, help_text="'Typical Focus' description. Leave blank for a simple tile."),
        ),
        migrations.AddField(
            model_name='servicefeatureitem',
            name='tag_label',
            field=models.CharField(blank=True, help_text="Small badge overlaid on the photo, e.g. 'Engineering & Field Ops'. Role cards only.", max_length=60),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_button_label',
            field=models.CharField(blank=True, help_text="Leave blank for the default Call Now/WhatsApp banner. Set this (e.g. 'Request Training') to show a single button instead, with the photo above as its background.", max_length=60),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_button_url',
            field=models.URLField(blank=True, help_text='Where the single CTA button links. Defaults to the Contact page.'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='cta_image',
            field=models.ImageField(blank=True, help_text='Optional background photo for the CTA banner (only used with the single-button style below).', null=True, upload_to='services/cta/'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='gallery_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='gallery_title',
            field=models.CharField(blank=True, help_text='Leave blank to hide this section.', max_length=150),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_badge_4_icon',
            field=models.CharField(blank=True, choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], max_length=20),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_badge_4_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='overview_eyebrow',
            field=models.CharField(blank=True, help_text="e.g. 'Opportunities at MedEx Biomed'", max_length=80),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='secondary_eyebrow',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='secondary_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='secondary_title',
            field=models.CharField(blank=True, help_text='Leave blank to hide this section.', max_length=150),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='form_type',
            field=models.CharField(choices=[('support_demo', 'Support & Demo Request (equipment/product fields)'), ('training_enquiry', 'Training Enquiry (course/schedule fields)'), ('career_application', 'Career Application (resume upload + candidate fields)'), ('general', 'General enquiry (name, email, message only)')], default='support_demo', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.servicepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceValueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='check', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_items', to='core.servicepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
