# Generated by Django 5.0.7 on 2026-09-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage_resume_servicefeatureitem_apply_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_badge_4',
            field=models.CharField(blank=True, help_text="Optional 4th badge — used by the 'badge_heavy' layout.", max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_layout',
            field=models.CharField(choices=[('circular_image', 'Circular photo + short tagline (e.g. patient-facing app)'), ('dashboard_mockup', 'Dark dashboard/window mockup + tagline (e.g. clinician tools)'), ('photo_card', 'Small photo card + tagline (e.g. simple product)'), ('badge_heavy', 'No device graphic — larger title + many trust badges (e.g. hardware/devices)')], default='circular_image', help_text='Which hero visual style to use for this product.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sidebar_note_cta_label',
            field=models.CharField(blank=True, help_text="e.g. 'Request Spec Sheet (PDF)'", max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='sidebar_note_cta_url',
            field=models.URLField(blank=True, help_text='Leave blank to link to the Contact page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='sidebar_note_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='sidebar_note_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='sidebar_note_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sidebar_note_title',
            field=models.CharField(blank=True, help_text="Leave blank to hide. e.g. 'Clinical Specialist Assistance'.", max_length=100),
        ),
    ]
