# Generated by Django 5.0.7 on 2026-09-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_hero_badge_4_product_hero_layout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_title', models.CharField(default='Send Us an Enquiry', max_length=150)),
                ('form_description', models.TextField(blank=True)),
                ('details_eyebrow', models.CharField(blank=True, default='Support & Reach', max_length=80)),
                ('details_title', models.CharField(default='Our Contact Details', max_length=150)),
                ('details_subtitle', models.CharField(blank=True, max_length=200)),
                ('highlights_intro', models.TextField(blank=True, help_text="Short intro line above the support-highlights checklist, e.g. 'We're always here to support your healthcare technology needs.'")),
                ('map_eyebrow', models.CharField(blank=True, default='Location', max_length=80)),
                ('map_title', models.CharField(default='Find Us on Map', max_length=150)),
                ('map_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Head Office — Chennai'", max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, help_text='Leave blank to use the site-wide phone number.', max_length=30)),
                ('map_embed_url', models.URLField(blank=True, help_text="Google Maps 'Embed a map' iframe src URL for this location.")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='approach_text',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='approach_title',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='mission_text',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontent',
            name='mission_title',
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hero_badge_title',
            field=models.CharField(blank=True, help_text="e.g. 'Technology In Safe Hands'", max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hero_highlight_label',
            field=models.CharField(blank=True, help_text="e.g. 'Operational Precision Standards'", max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hero_highlight_value',
            field=models.CharField(blank=True, help_text="e.g. '10y+'", max_length=20),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hero_status_text',
            field=models.CharField(blank=True, help_text="e.g. 'Emergency Clinical Support Available'", max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='leadership_eyebrow',
            field=models.CharField(blank=True, default='About Director & Founder', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='leadership_title',
            field=models.CharField(blank=True, default='Leadership Driving Medical Excellence', max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_caption_eyebrow',
            field=models.CharField(blank=True, help_text="e.g. 'Proven Excellence'", max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_caption_text',
            field=models.CharField(blank=True, help_text="e.g. 'Trusted by Healthcare Providers Across the Region'", max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_eyebrow',
            field=models.CharField(blank=True, default='Our Story', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/story/'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_image_badge',
            field=models.CharField(blank=True, help_text="e.g. 'Medex Biomed Headquarters'", max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_paragraph_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='story_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_choose_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_choose_eyebrow',
            field=models.CharField(blank=True, default='Why Choose Us', max_length=80),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_choose_title_highlight',
            field=models.CharField(blank=True, help_text="e.g. 'A Long-Term Partnership' (shown in red)", max_length=150),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='why_choose_title_main',
            field=models.CharField(blank=True, help_text="e.g. 'More Than Service, '", max_length=150),
        ),
        migrations.AddField(
            model_name='pageintro',
            name='image',
            field=models.ImageField(blank=True, help_text="Optional hero photo/graphic for this page (e.g. the Contact page's hero image).", null=True, upload_to='page-intros/'),
        ),
        migrations.AddField(
            model_name='pageintro',
            name='title_highlight',
            field=models.CharField(blank=True, help_text="Optional final word(s) of the title shown in red, e.g. 'Reliable Healthcare'. Leave blank for a single-color title.", max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='domain_expertise',
            field=models.CharField(blank=True, help_text="e.g. 'Critical Care & Device Governance'", max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='operational_base',
            field=models.CharField(blank=True, help_text="e.g. 'Chennai & South India Networks'", max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='prior_leadership',
            field=models.CharField(blank=True, help_text="e.g. 'Regional Manager, Colmed (8 yrs)'", max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='quote_label',
            field=models.CharField(blank=True, default='Leadership Philosophy', max_length=60),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='ecosystem_core_label',
            field=models.CharField(blank=True, default='Central Foundation', max_length=60),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='ecosystem_core_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='ecosystem_core_title',
            field=models.CharField(blank=True, default='MedEx Biomed Core', max_length=100),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='ecosystem_eyebrow',
            field=models.CharField(blank=True, default='Unified Operational Framework', max_length=80),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='ecosystem_footer_badge_1',
            field=models.CharField(blank=True, help_text="e.g. 'NABL & NABH Traceable'", max_length=60),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='ecosystem_footer_badge_2',
            field=models.CharField(blank=True, help_text="e.g. 'ISO Standards Aligned'", max_length=60),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='ecosystem_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='ecosystem_title',
            field=models.CharField(blank=True, default='The MedEx Biomed Ecosystem', max_length=150),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='mission_title',
            field=models.CharField(blank=True, help_text="Short heading, e.g. 'Fortifying Healthcare Infrastructure & Protecting Patient Lives'.", max_length=200),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='network_benchmark_subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='network_benchmark_tag',
            field=models.CharField(blank=True, default='Benchmark', max_length=40),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='network_benchmark_title',
            field=models.CharField(blank=True, help_text="e.g. 'Zero Equipment Downtime'", max_length=100),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='network_panel_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='network_panel_status_label',
            field=models.CharField(blank=True, help_text="e.g. '99.98% Active'", max_length=40),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='network_panel_title',
            field=models.CharField(blank=True, default='Live Asset Network Status', max_length=100),
        ),
        migrations.AddField(
            model_name='visionmission',
            name='vision_title',
            field=models.CharField(blank=True, help_text="Short heading, e.g. 'To Be the Premier Clinical Technology & Biomedical Partner'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='badge_text',
            field=models.CharField(blank=True, help_text="e.g. 'Verified Bio-Engineer' / 'Technical Leader'", max_length=80),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text="Full biography for the About page's leadership profile. Separate paragraphs with a blank line."),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_leadership',
            field=models.BooleanField(default=False, help_text="Show in the homepage 'Our Leadership' section and the About page's full profile."),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='quote',
            field=models.CharField(blank=True, help_text='Pull-quote shown on the homepage and About page.', max_length=250),
        ),
        migrations.CreateModel(
            name='ContactHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contact_page_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.contactpagecontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('vision_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_pillars', to='core.visionmission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisionHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('vision_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.visionmission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisionStatusRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('vision_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_rows', to='core.visionmission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='check', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_items', to='core.aboutpagecontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
