# Generated by Django 5.0.7 on 2026-09-22 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactpagecontent_officelocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text="e.g. 'Biomedical Engineering · Digital Health · Better Care'", max_length=100)),
                ('title_main', models.CharField(blank=True, help_text="e.g. 'Keeping Healthcare Technology Running '", max_length=200)),
                ('title_highlight', models.CharField(blank=True, help_text="e.g. 'When It Matters Most.' (shown in the accent color)", max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, help_text='Full-width background photo for the hero banner.', null=True, upload_to='home/hero/')),
                ('primary_button_label', models.CharField(blank=True, help_text="e.g. 'Explore Our Services'", max_length=60)),
                ('primary_button_url', models.CharField(blank=True, help_text="e.g. '/services'", max_length=200)),
                ('secondary_button_label', models.CharField(blank=True, help_text="e.g. 'Get a Quote'", max_length=60)),
                ('secondary_button_url', models.CharField(blank=True, help_text="e.g. '/contact'", max_length=200)),
            ],
            options={
                'verbose_name': 'Homepage Hero Banner',
                'verbose_name_plural': 'Homepage Hero Banner',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': "Homepage 'Who We Are' Section", 'verbose_name_plural': "Homepage 'Who We Are' Section"},
        ),
        migrations.AlterModelOptions(
            name='ecosystempillar',
            options={'ordering': ['order'], 'verbose_name': 'Homepage Ecosystem Card', 'verbose_name_plural': 'Homepage Ecosystem Cards'},
        ),
        migrations.AlterModelOptions(
            name='operatingpillar',
            options={'ordering': ['order'], 'verbose_name': 'Homepage Operating Pillar', 'verbose_name_plural': 'Homepage Operating Pillars'},
        ),
        migrations.CreateModel(
            name='HomeTrustPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='check', max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_points', to='core.homehero')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
