# Generated by Django 5.0.7 on 2026-09-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_homehero_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='concept_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='concept_title',
            field=models.CharField(blank=True, default='THERMACHECK SCREENING CONCEPT', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='software_suite_title',
            field=models.CharField(blank=True, default='OPTIMIZED IN MEDICAL USE (SOFTWARE SUITE)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_sheet_pdf',
            field=models.FileField(blank=True, help_text='Downloadable spec sheet PDF file.', null=True, upload_to='products/pdfs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='why_use_points',
            field=models.TextField(blank=True, help_text="One 'Why use' bullet point per line."),
        ),
        migrations.AddField(
            model_name='product',
            name='why_use_title',
            field=models.CharField(blank=True, default='WHY SHOULD YOU USE THERMACHECK?', max_length=150),
        ),
        migrations.CreateModel(
            name='ProductSoftwareCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(blank=True, help_text="e.g. 'AUTO ROI', 'AI ASSIST'", max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('footer_text', models.CharField(blank=True, help_text="e.g. 'Automated Contouring', '53 Disease Profiles'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_cards', to='core.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
