# Generated by Django 5.0.7 on 2026-09-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_concept_description_product_concept_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='poster_subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='poster_title',
            field=models.CharField(blank=True, help_text='Leave blank to hide this section.', max_length=150),
        ),
        migrations.AddField(
            model_name='teammember',
            name='about_quote',
            field=models.TextField(blank=True, help_text='Detailed quote/philosophy shown on the About page profile.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='quote',
            field=models.CharField(blank=True, help_text='Pull-quote shown on the homepage.', max_length=250),
        ),
        migrations.CreateModel(
            name='ServicePosterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='services/posters/')),
                ('title', models.CharField(blank=True, help_text='Optional caption shown under the poster in the popup.', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_items', to='core.servicepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
