# Generated by Django 5.0.7 on 2026-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicepage_poster_subtitle_servicepage_poster_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecosystempillar',
            name='icon',
        ),
        migrations.AddField(
            model_name='ecosystempillar',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ecosystem/logos/'),
        ),
    ]
