# Generated by Django 5.0.7 on 2026-09-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_ecosystempillar_icon_ecosystempillar_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sidebar_note_support_label',
            field=models.CharField(blank=True, default='TECHNICAL SUPPORT', help_text="Label above phone/email, e.g. 'TECHNICAL SUPPORT'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sidebar_note_text',
            field=models.TextField(blank=True, default='Need turnkey installation guidance or ROI estimation for your diagnostic center?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sidebar_note_title',
            field=models.CharField(blank=True, default='Clinical Specialist Assistance', help_text='Leave blank to hide.', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, choices=[('shield', 'Shield (compliance / safety)'), ('clock', 'Clock (experience / time)'), ('monitor', 'Monitor (equipment / software)'), ('building', 'Building (facilities / trust)'), ('check', 'Check (verified / quality)'), ('wrench', 'Wrench (maintenance / repair)'), ('video', 'Video (telehealth / remote)'), ('chart', 'Chart (diagnostics / analytics)'), ('package', 'Package (spares / equipment)'), ('link', 'Link (integration / ecosystem)'), ('file', 'File (documentation / traceability)'), ('bolt', 'Bolt (rapid response)'), ('eye', 'Eye (vision)'), ('headset', 'Headset (support)'), ('users', 'Users (team)'), ('heart', 'Heart (patient monitoring)'), ('flask', 'Flask (lab / diagnostics)'), ('calendar', 'Calendar (scheduling)')], default='wrench', max_length=20),
        ),
    ]
